
package com.develogment.sod.ui.second;

import com.develogment.sod.dal.MoviesWorldwideDAO;
import com.develogment.sod.dal.SalesByStoreDAO;
import com.rapidclipse.framework.server.charts.Background;
import com.rapidclipse.framework.server.charts.ChartModel;
import com.rapidclipse.framework.server.charts.Column;
import com.rapidclipse.framework.server.charts.Column.Type;
import com.rapidclipse.framework.server.charts.FocusTarget;
import com.rapidclipse.framework.server.charts.Legend;
import com.rapidclipse.framework.server.charts.Legend.Position;
import com.rapidclipse.framework.server.charts.StackMode;
import com.rapidclipse.framework.server.charts.TextStyle;
import com.rapidclipse.framework.server.charts.bar.ColumnChart;
import com.rapidclipse.framework.server.charts.pie.PieChart;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "second", layout = Cat2MainContainer.class)
public class Cat2ViewSecond extends VerticalLayout
{

	public Cat2ViewSecond()
	{
		super();
		this.initUI();
		
/*
Hier wird einen Chart erstellt und in dem unsere benötigte Daten dargestellt werden 
*/
		final ChartModel model = ChartModel.New()
			.addColumn(Column.New(Type.STRING))
			.addColumn(Column.New(Type.NUMBER));
		
		SalesByStoreDAO.INSTANCE.findAll().forEach(p -> {
			model.addRow(p.getId().getStore(), p.getId().getTotalSales());
			
		});
		
		this.pieChart.setBackground(Background.Color("#b3b184"));
		this.pieChart.setModel(model);
		this.pieChart.setIs3D(true);
		
		final ChartModel table = ChartModel.New()
			.addColumn(Column.New(Type.STRING, "Production Countries", "Production Countries"))
			.addColumn(Column.New(Type.NUMBER, "Average", "Average Production Budget "))
			.addColumn(Column.New(Type.NUMBER, "Number of Movies", "Number of Movies "))
			.addColumn(Column.New(Type.NUMBER, "Total Worldwide Box Office", "Total Worldwide Box Office"));
		
		MoviesWorldwideDAO.INSTANCE.findAll().forEach(p -> {
			table.addRow(p.getProductionCountries(), p.getAverageProductionBudget(),
				p.getNoOfMovies(), p.getTotalWorldwideBoxOffice());
			
		});
		final TextStyle textStyle = TextStyle.Builder()
			.fontSize(20)
			.build();
		this.columnChart.setTitleTextStyle(textStyle);
		this.columnChart.setStackMode(StackMode.TRUE);
		this.columnChart.setModel(table);
		final Legend legend = Legend.Builder()
			.position(Position.RIGHT)
			.maxLines(5)
			.build();
		this.columnChart.setLegend(legend);
		this.columnChart.setBackground(Background.Color("#b3b184"));
	}

	// add name and number of occurrences of client to chart

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.lblContent        = new Label();
		this.verticalLayout    = new VerticalLayout();
		this.horizontalLayout2 = new HorizontalLayout();
		this.horizontalLayout  = new HorizontalLayout();
		this.columnChart       = new ColumnChart();
		this.pieChart          = new PieChart();

		this.lblContent.setText(" Chart");
		this.lblContent.getStyle().set("font-size", "5em");
		this.columnChart.setTitle("Movie Production Countries ");
		this.columnChart.setFocusTarget(FocusTarget.CATEGORY);
		this.pieChart.setTitle("Total Sales by Store Location");
		this.pieChart.setChartHeight(500);
		this.pieChart.setIs3D(true);
		this.pieChart.setChartWidth(500);
		this.pieChart.setFontName("");
		this.pieChart.setPieStartAngle(50);
		this.pieChart.setSliceVisibilityThreshold(0.0018F);
		this.pieChart.setPieHole(2);
		this.pieChart.setFontSize(18);

		this.columnChart.setWidthFull();
		this.columnChart.setHeight(null);
		this.pieChart.setWidthFull();
		this.pieChart.setHeight(null);
		this.horizontalLayout.add(this.columnChart, this.pieChart);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.CENTER, this.pieChart);
		this.horizontalLayout2.setWidthFull();
		this.horizontalLayout2.setHeight(null);
		this.horizontalLayout.setWidth("948px");
		this.horizontalLayout.setHeight(null);
		this.verticalLayout.add(this.horizontalLayout2, this.horizontalLayout);
		this.lblContent.setSizeUndefined();
		this.verticalLayout.setWidthFull();
		this.verticalLayout.setHeight(null);
		this.add(this.lblContent, this.verticalLayout);
		this.setWidthFull();
		this.setHeight(null);
	} // </generated-code>
	
	// <generated-code name="variables">
	private VerticalLayout   verticalLayout;
	private HorizontalLayout horizontalLayout2, horizontalLayout;
	private Label            lblContent;
	private ColumnChart      columnChart;
	private PieChart         pieChart;
	// </generated-code>
	
}
