
package com.develogment.sod.ui.second;

import com.vaadin.flow.component.dependency.HtmlImport;
import com.vaadin.flow.component.html.Label;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "", layout = Cat2MainContainer.class)
@HtmlImport("frontend://styles/shared-styles.html")
public class Cat2Main extends VerticalLayout
{
	public Cat2Main()
	{
		super();
		this.initUI();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.lblContent = new Label();
		
		this.lblContent.setText("media");
		this.lblContent.getStyle().set("font-size", "5em");
		
		this.lblContent.setSizeUndefined();
		this.add(this.lblContent);
		this.setWidthFull();
		this.setHeight(null);
	} // </generated-code>
	
	// <generated-code name="variables">
	private Label lblContent;
	// </generated-code>
	
}
