
package com.develogment.sod.ui.second;

import com.develogment.sod.domain.Product;
import com.rapidclipse.framework.server.ui.navigation.NavigationSideBar;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Image;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.FlexLayout;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;


@Route(value = "first", layout = Cat2MainContainer.class)
public class Cat2ViewFirst extends VerticalLayout
{
	Product product;
	
	public Cat2ViewFirst()
	{
		super();
		this.initUI();
		
	}
	
	private Image convertImage(final byte[] imageData)
	
	{
		
		final Image convertImage = this.convertImage(imageData);
		return convertImage;
	}
	
	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer.
	 * Chancen und Risiken der künstlichen Intelligenz. SWOT-Analyse und Anwendungsgebiete der Technologie
	 * Big Data in der Informationstechnologie. Chancen und Risiken der IT-Branche
	 * Big Data im Marketing. Nutzen, Chancen und Herausforderungen für kleine und mittelständische Unternehmen
	 */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.h3                = new H3();
		this.horizontalLayout  = new HorizontalLayout();
		this.navigationSideBar = new NavigationSideBar();
		this.flexLayout        = new FlexLayout();
		this.div2              = new Div();
		this.div3              = new Div();
		this.div               = new Div();
		this.image             = new Image();
		
		this.setMinHeight("0");
		this.setSpacing(false);
		this.getStyle().set("overflow-x", "hidden");
		this.getStyle().set("overflow-y", "auto");
		this.h3.setText("images");
		this.flexLayout.setJustifyContentMode(FlexComponent.JustifyContentMode.BETWEEN);
		
		this.image.setWidth("100px");
		this.image.setHeight("100px");
		this.div.add(this.image);
		this.div2.setWidth("100px");
		this.div2.setHeight("100px");
		this.div3.setWidth("100px");
		this.div3.setHeight("100px");
		this.div.setWidth("100px");
		this.div.setHeight("100px");
		this.flexLayout.add(this.div2, this.div3, this.div);
		this.navigationSideBar.setWidth(null);
		this.navigationSideBar.setHeight("400px");
		this.flexLayout.setWidthFull();
		this.flexLayout.setHeight(null);
		this.horizontalLayout.add(this.navigationSideBar, this.flexLayout);
		this.horizontalLayout.setVerticalComponentAlignment(FlexComponent.Alignment.START, this.navigationSideBar);
		this.h3.setSizeUndefined();
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.add(this.h3, this.horizontalLayout);
		this.setSizeUndefined();
	} // </generated-code>

	// <generated-code name="variables">
	private FlexLayout        flexLayout;
	private Image             image;
	private NavigationSideBar navigationSideBar;
	private HorizontalLayout  horizontalLayout;
	private Div               div2, div3, div;
	private H3                h3;
	// </generated-code>
	
}
