
package com.develogment.sod.ui.util;

import java.net.URI;

import com.vaadin.flow.component.Component;
import com.vaadin.flow.component.DetachEvent;
import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.dependency.NpmPackage;
import com.vaadin.flow.dom.Element;
import com.vaadin.flow.server.StreamRegistration;
import com.vaadin.flow.server.StreamResource;
import com.vaadin.flow.server.StreamResourceRegistry;
import com.vaadin.flow.server.VaadinSession;


@NpmPackage(value = "@lrnwebcomponents/pdf-browser-viewer", version = "2.7.10")
@JsModule("@lrnwebcomponents/pdf-browser-viewer/pdf-browser-viewer.js")
@Tag("pdf-browser-viewer")
public class PdfBrowserViewer extends Component
{
	private StreamRegistration streamRegistration;
	
	public PdfBrowserViewer()
	{
		super();
		// TODO Auto-generated constructor stub
	}
	
	public PdfBrowserViewer(final StreamResource streamResource)
	{
		super();
		this.setStreamResource(streamResource);
	}
	
	public void setStreamResource(final StreamResource streamResource)
	{
		this.unregister();
		this.streamRegistration = VaadinSession.getCurrent().getResourceRegistry().registerResource(streamResource);
		final URI uri = StreamResourceRegistry.getURI(streamResource);
		this.setFile(uri.toASCIIString());
	}
	
	public void setFile(final String file)
	{
		this.getElement().setAttribute("file", file);
	}
	
	public void setNotSupportedMessage(final String message)
	{
		this.getElement().setAttribute("not-supported-message", message);
	}
	
	public void setNotSupportedLinkMessage(final String message)
	{
		this.getElement().setAttribute("not-supported-link-message", message);
	}
	
	public void setCard(final boolean card)
	{
		this.getElement().setAttribute("card", card);
	}
	
	public void setDownloadLabel(final String label)
	{
		this.getElement().setAttribute("downloadLabel", label);
	}
	
	public void setElevation(final String elevation)
	{
		this.getElement().setAttribute("elevation", elevation);
	}
	
	public void setHeight(final String height)
	{
		this.getElement().setAttribute("height", height);
		this.getElement().getStyle().set("height", height);
	}
	
	public void setWidth(final String width)
	{
		this.getElement().setAttribute("width", width);
		this.getElement().getStyle().set("width", width);
	}
	
	@Override
	protected void onDetach(final DetachEvent detachEvent)
	{
		super.onDetach(detachEvent);
		this.unregister();
	}
	
	private void unregister()
	{
		if(this.streamRegistration != null)
		{
			this.streamRegistration.unregister();
		}
	}
	
	public PdfBrowserViewer(final Element element)
	{
		super();
	}
	
	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
	} // </generated-code>

}
